guy_cnet_homepage:
    pattern:  /Home
    defaults: { _controller: GuyCnetBundle:Default:index }

guy_cnet_portfolio:
    pattern:  /Portfolio
    defaults: { _controller: GuyCnetBundle:Portfolio:index }
